addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.4")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"     % "5.6.0")
addSbtPlugin("com.lightbend.paradox"     % "sbt-paradox"    % "0.8.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"       % "1.4.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-ghpages"    % "0.6.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.14")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"    % "0.5.1")
